language: java

jdk:
  - openjdk11

services:
  - docker

install: skip

script:
  - cd lnshop
  - bash ./mvnw clean package -Dmaven.test.skip=true
  - docker build -t jctiru/lnshop-backend .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jctiru/lnshop-backend
  - curl --silent --output /dev/null  --request POST https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/ref/$REF_NAME/trigger/pipeline?token=$GITLAB_TRIGGER_TOKEN

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
