version: "3.5"

services: 
  lnshop-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes:
      - openj9-shareclasses:/opt/app/jvm/openj9/shareclasses
    env_file: 
      - ./docker-compose-secrets/secrets.env
    deploy:
      resources:
        limits:
          cpus: "2"
        reservations:
          memory: 150M

volumes:
  openj9-shareclasses:

# docker-compose --compatibility up (--build)